<<<<<<< HEAD
# Intermediate Project Practice

## Complex Projects {.unnumbered}

<br /> In this unit, we will delve into more intricate and comprehensive projects, striving towards mature works in terms of program implementation and design of appearance structure. These include miniaturized smart homes, wearable electronic devices, interactive electronic instruments, Wi-Fi connectivity, and applications enabled by XIAO ESP32C3 or telemetry and command via the MQTT protocol. We will provide the laser-cut design blueprints for the first three cases for your reference. Of course, you're not limited to these examples; you could use other, more accessible materials, such as corrugated cardboard or cardstock, for crafting. Feel free to unleash your creativity and design the work you wish to present!
=======
# Chapter 3: Intermediate Project Practice---Complex Projects
<br />
In this unit, we will delve into more intricate and comprehensive projects, striving towards mature works in terms of program implementation and design of appearance structure. These include miniaturized smart homes, wearable electronic devices, interactive electronic instruments, Wi-Fi connectivity, and applications enabled by XIAO ESP32C3 or telemetry and command via the MQTT protocol. We will provide the laser-cut design blueprints for the first three cases for your reference. Of course, you're not limited to these examples; you could use other, more accessible materials, such as corrugated cardboard or cardstock, for crafting. Feel free to unleash your creativity and design the work you wish to present!
>>>>>>> a620d1503eb9ae9997a7c6750132f44f1d0f7d3a
